using MetaGen.Contracts;

namespace LifeStream.Domain.Sources;

/// <summary>
/// Base configuration for an information source.
/// Generated by MetaGen from metadata.json.
/// </summary>
[MetaGen("InformationSource")]
public partial class InformationSource
{
}
