using MetaGen.Contracts;

namespace LifeStream.Domain.Dashboard;

/// <summary>
/// Saved dashboard layout configuration.
/// Generated by MetaGen from metadata.json.
/// </summary>
[MetaGen("DashboardLayout")]
public partial class DashboardLayout
{
}
