using MetaGen.Contracts;

namespace LifeStream.Domain.Data;

/// <summary>
/// Alert or notification from an information source.
/// Generated by MetaGen from metadata.json.
/// </summary>
[MetaGen("Alert")]
public partial class Alert
{
}
