using MetaGen.Contracts;

namespace LifeStream.Domain.Data;

/// <summary>
/// Time series data point from an information source.
/// Generated by MetaGen from metadata.json.
/// </summary>
[MetaGen("DataPoint")]
public partial class DataPoint
{
}
