using MetaGen.Contracts;

namespace LifeStream.Domain.Configuration;

/// <summary>
/// User preferences and application settings.
/// Properties are generated by MetaGen from metadata.json.
/// </summary>
[MetaGen("UserSettings")]
public partial class UserSettings
{
    // Generated properties will appear in UserSettings.g.cs
    // Add any custom business logic methods here
}
